[tool.isort]
force_alphabetical_sort_within_sections = true
force_single_line = true
from_first = false
line_length = 125
lines_after_imports = 2
skip = "manage.py, wsgi.py"
skip_glob = "venv,include,lib,bin"
