# Generated by Django 3.1.3 on 2021-03-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.taskgroup'),
        ),
    ]
